repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0  # Use latest release
    hooks:
      - id: ruff
        args: ["--fix"]  # auto-fix linting issues
      - id: ruff-format  # optional: enable ruff formatter too
