name: CI
on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/set-python@v5
      with:
        python-version: "3.11" # change to your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run tests
      run: |
        pytest --cov=service tests/

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
