name: Run Pytest on Pull Request

on:
  pull_request:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Adjust this if you use a different dependency file

    - name: Run Pytest
      run: |
        pytest